setwd("~/usr/doc/uninotes/Y1S1/STAT1008/ST1008AS1")
setwd("/Users/j/Documents/UniNotes/Y1S1/STAT1008/ST1008AS1/")
aq = read.csv("airquality.csv")
hist(aq$Temp, breaks=20)
#Save currently visible plot
boxplot(Ozone~Month,data=aq, main="Ozone per Month", ylab="Ozone Density", xlab="Month")
plot(table(aq$Ozone, aq$Temp))
plot(aq$Temp, aq$Ozone, main="Ozone Density for Temperature", ylab="Ozone Density", xlab="Temperature (°F)") 
cov(aq$Wind,aq$Ozone, use="complete.obs")
plot(cor(aq$Temp, aq$Ozone, use="complete"))
