setwd("~/usr/doc/uninotes/Y1S1/STAT1008/ST1008AS1")
setwd("/Users/j/Documents/UniNotes/Y1S1/STAT1008/ST1008AS1/")
aq = read.csv("airquality.csv")
hist(aq$Temp, breaks=20)
boxplot(Ozone~Month,data=aq, main="Ozone per Month", ylab="Ozone Density", xlab="Month")
plot(table(aq$Ozone, aq$Temp))
plot(aq$Temp, aq$Ozone, main="Ozone Density for Temperature", ylab="Ozone Density", xlab="Temperature (°F)") 
cov(aq$Wind,aq$Ozone, use="complete.obs")
cor(aq$Temp[aq$Month==5], aq$Ozone[aq$Month==5], use="complete.obs")
cor(aq$Temp[aq$Month==6], aq$Ozone[aq$Month==6], use="complete.obs")
cor(aq$Temp[aq$Month==7], aq$Ozone[aq$Month==7], use="complete.obs")
cor(aq$Temp[aq$Month==8], aq$Ozone[aq$Month==8], use="complete.obs")
cor(aq$Temp[aq$Month==9], aq$Ozone[aq$Month==9], use="complete.obs")
cov(aq,use="complete.obs")
cor(aq$Wind, aq$Ozone, use="complete.obs")
sum(aq$Wind - mean(aq$Wind))

