#+LATEX_HEADER: \usepackage{amsmath,cancel}
* MATH1013
** COURSE INFO
- Tutorial quizzes (best 8 of 10) - 10%
- Other tutorial work - 2.5%
- Online WebAssign quizzes (best 8 of 10) - 105
- David does mostly Mon & Tue, Calc
- tutes week 3
- online quiz must be done by Sunday *before* tutorial
- need to sign in for WebAssign p soon
- must keep a written record of the online quizzes, checked in week 11-12, that's the workbook for this one

* WK1
** L1
   
Read 1.1-1.3 of Stewart calculus textbook by next week (probs need to pick it up)

** L2
Calculus Course Outline available in the book i think

Consultation hours for David are after lecture on Monday 3-4pm JD2146

Don't forgot to read Stewart 1.1-1.3 by Monday

  _Functions_
For this course, only using real numbers for inputs and outputs

To specify a function:
- a rule
- a set of possible inputs (known as the _domain_)
  
Domain notation:
- \real - real numbers
- (a,b) = {x \elem \real:a<x<b}
- [a,b] ={x \elem \real:a=<x=<b}
- N = {0,1,2,3,...}
- Z = {...,-3,-2,-1,0,1,2,3,...}
- Q = { $\frac{a}{b}$: a,b are integers}
  
  _Examples of Functions_
f(x)=x^3 on [0,\infin)

f(x)=x+1 on N

f(x)=$\frac{1}{x^2}$ on [-1,0)\cup(0,1]

   
_Maximal Domain of a Function_: the largest set of real numbers on which the function can be defined 

3 points to remember:
- Can't divide by zero
- Can't take the root of -ve numbers
- Can't log -ve numbers

_Range of a Function_: the set of all output values on the domain

** L3
   _Algebra_

Lecturer for this part is... very quiet

$\frac{1}{x}$ is non-linear

How can we describe the solutions to $3x+7y-z+2w=0$? 
- 3D /hyperplane/ in 4D space

Complex numbers show up at the end! Hooray!

Consistent:
- one (unique) solution
- \infin many solutions

Inconsistent:
- no solutions
  
_Interpolation_

Fitting a function to something

* WK2
 Drop-in sessions will start this week
 Sections 1.4-1.6 calc (get the textbook you fuck)
** L1
*** Limits
_Definition_: Suppose $f(x)$ is defined on some open interval containing $a$, except possibly at $a$ itself. Then we say $$\lim_{x \rightarrow a}f(x)=L$$ if we can make $f(x)$ arbitrarily close to $L$ by taking $x$ sufficiently close to $a$.

_Ex._: $\lim_{x \rightarrow a}x^{2}=1$

_Reminder_: $f(a)$ has nothing to do with $\lim_{x \rightarrow a}f(x)$
    
_Ex._: \[g(x) = \begin{cases}
x^{2} & x \neq 1 \\
21 & x=1
\end{cases}, \mbox{ } lim_{x \rightarrow 1}g(x)=1_{}\]

_Proposition_: suppose $f(x),g(x)$ are defined near $a$ but possibly not at $a$ itself. If $f(x)=g(x)$ for all $x$ near $a$, then $$\lim_{x \rightarrow a}f(x)=\lim_{x \rightarrow a}g(x)$$  

_Ex._: $$\lim_{x \rightarrow 2}\frac{x^{2}-4}{x-2}$$
- factorise numerator, can see $(x+2)$ remains post-cancel
- observe that $\frac{x^{2}-4}{x-2} = x+2 \mbox{ when } x\ne0$

$$\lim_{x \rightarrow 2}\frac{x^{2}-4}{x-2}=\lim_{x\rightarrow2}x+2$$
$$\therefore\lim_{x \rightarrow 2}\frac{x^{2}-4}{x-2}=4$$

