* FINM2003: Investments
- Mid Sem 20%
- Group Assignment 20%
- Final 60%

* Wk 1 - Introduction To Investments
** Lecture 1
- No workshop tomorrow

An investment is the /current/ commitment of money or other resources in theexpectation of reaping /future/ benefits
- Timing: current vs future, today vs tomorrow
- Other resources: time, land , labour, emotion
- Expectation: certain level of uncertainty (risk)
- Future benefits: monetary or non-monetary

*** Real assets vs Financial Assets_

*Real assets*:
- Land
- Buildings
- Machines
- Knowledge
- Can be used to produce goods and economy
- Generate net income to the economy

*Financial assets*:
- Stocks
- Bonds
- Claims to the income generated by real assets
- Define the allocation of income or wealth among investors.

*Fixed income or debt securities*: promise ethier a fixed stream of incom or a stream of income determined by a specific pormula

*Common stock or equity*: Represents an ownership share in a corporation

*Derivative Securities*: Provides payoffs that are determined by the prices of other assets such as bond or stock prices

*** The Investment Process

*Portfolio*: collection of investment assets

Once established, update/rebalance by:
- Selling existing securities and using proceeds to buy new securities
- Investing funds to increase the size of the portfolio
- Selling securities to decrease the size of the portfolio

Investment process = Portfolio construction

Two types of decisions:
- Asset Allocation: choice /among/ broad asset classes
- Something else god fuck him

*Security analysis*: valuation of securities that might be included in the portfolio

*"Top-down" approach*: starts with asset allocation, followed by security analysis

*"Bottom-up" approach*: based solely on securities' price-attractiveness

*** Financial markets and the economy

Informational role of financial markets. 
Stock prices reflect investors' collective assessment of a firms current performance and future prospects.

Consumption timing (smoothing)

Allocation of risk.

Separation of ownership and management (agency problem).

Corporate governance and corporate ethics.

**** Financial markets

Can be segmented into
- Money Markets
  - Include short-term, marketable, liquid, low-risk debt securities
  - Called cash equivalents or cash for short.
- Capital markets.
  - Include long-term and riskier securities.
  - Much more diverse comparing to money market.
  - Four segments:
  - Longer term bond markets.
  - Equity markets.
  - Derivative markets.
  - Options and Futures.

***** Money market

Money market instruments include:
- Treasury Bils
- Certificates of deposit
- Commercial paper
- Repos and Reverses

Money market securities are very short-term debt obligations, highly marketable and relatively low-risk. 
Low maturities and low credit risk ensure minimal capital gains and losses.
Traded in large denominations, but can be purchased indirectly through money market funds.

***** Bond market

Bond market instruments include:
- Treasury notes and bonds (maturities up to 10 years (notes), or 10-30 (bonds))
- Inflation-protected treasury bonds
- Federal agency debt
- International bonds
- Municipal bonds, issued by both local and state governments
- Corporate bonds
- Mortgages and mortgage-backed securities

***** Equity securities

Common stocks = equity securites (equities)
- Repr. ownership shares in corp.
- Entitles owner to vote

Characteristics of common stocks:
- *Residual claim*. SH are the last in line of all who have a claim on assets and income of corp.
- Limited liability
  - At worst worthless stock in the event of failure
  - Not personally liable for the firm's obligations

***** Stock market indexes

Stock index corresponds to a portfolio of stocks

*Price-weighted average*: ((example, grab if possible for here (org table), but put it on paper))

*Stock splits*

$\frac{\mbox{Price of ABC + Price of XYZ}}{d}$ $d$ = divisor

*** How securities are traded

*Primary Market*:
- Market for newly-issued securities
- Firms issue new securities through the underwriters to the public

*Secondary Market*:
- Investors trade previously issude securities among themselves

**** Privately Held Firms / Publicly Traded companies

*Privately held firms*:
- Up to 499 shareholders
  - Middlemen formed partnerships to get around the restriction
- Raise funds through private placements
- Fewer obligations to release financial statments and other such information

*Public traded companies*:
- Raise funds from a wider range of investors, through IPOs (initial public offerings)
- Public offerings are marketed by investment bankers or underwriters
- Registration must be filed with the SEC

**** IPOs

Road shows to publicize new offering

Degree of investor interest in the new offering provides valuable pricing information

Underwriter bears price risk associated with placement of securities:
- IPOs commonly underpriced so they can be marketed better
- Some IPOs are well overpriced; others cannot even be fully sol

**** Type of Markets

- *Direct search*: buyers and sellers seek eachother
- *Brokered markets*: brokers search out buyers and sellers
- *Dealer markets*: dealers have inventories of assets from which they buy and sell
- *Auction markets*: traders converge at one place to trade

**** Bid and Asked Prices
Bid price: bids are offers to buy
Ask price: asked pricees represent offers to sell

**** Type of Orders

*Market order*: executed immediately, trader receives current market price

*Price contingent order*: Traders specify buying or selling prices

**** Trading Costs

*Brokerage Commission*: fee paid to broker for making the transaction

*Spread*: difference between the bid and asked prices

still got some shit to finish for this

* Week 2 - Risk, Return, and the Historical Record

** Lecture

*** Determinants of the Level of Interest Rates

These determinants include:
- Supply side (supply of funds from savers)
- Demand side (demand for funds from those who require more)
- Government's net demand (net supply of funds or demand for them)

*** Real and Nominal Rates of Interest

- *Nominal interest rate*: the growth rate of money
- *Real interest rate*: the growth rate of purchasing power

Suppose $r_{n}$ the nominal rate, $r_{r}$ the real rate, and $i$ the inflation rate. The approximation formula is: $$r_{r} \approx r_{n} - i$$ 
The *exact* relationship is $1 + r_{r} = \frac{1+r_{n}}{1+i}$, in the form of $$\mbox{growth of purchasing power} = \frac{\mbox{growth of money}}{\mbox{growth of prices}}$$

Investors are concerned with their real rate of interest because it measures the increase in their purchasing power. Given this, investors will demand higher nominal rates of return on their investments as expected inflation increases

*** Holding Period Returns

The holding period return (HPR) is a measure of the ruturn earned over a given investment period

$$HPR = \frac{\mbox{Investment Value}_{t} + \mbox{Investment Income}_{t} - \mbox{Investment Value}_{t-1}}{\mbox{Investment Value}_{t-1}}$$

The HPR calculation implicitly assumes that:
- investment income is received at the end of the holding period
- to the extent this is correct, ignores reinvestment income

Formula below with often yield the same result, this will not be when, for example, calculating the HPR on shares which undergo /capitalization changes/ during the holding period.

$$HPR = \frac{\mbox{Price}_{t} + \mbox{Income (e.g. Dividend)}_{t} - \mbox{Price}_{t-1}}{\mbox{Price}_{t-1}}$$

Given this, you should either use the other definition, or include /adjusted/ prices in the above formula

*** Summing/Average Returns over Time
(((((STUFF GOES HERE LUL)))))
Lots of forumlae and stuff go in this bit, write them out later though *with examples* because they're going to be shit otherwise

*** Geometric and Arithmetic Returns

*Aritmetic* average return is a good indication of the expected rate of return for an investment during a future individual year

*Geometric* average return assumes you:
- Reinvest all profits back into the stock
- The reinvested funds earn the rate of return the stock earns in subsequent periods
*More formulae to go in here* hand write them first, then add in them in here when you have the time to do it

If difference is more volatile, ????

The geoemetric return is more consistent with the actual return received by the investor
  
*** Comparing investments with Different Investment Horizons

Investments with longer horizons commonly earn greater HPRs. 

- HPRs on investments with different holding periods need to be stated as rates of return for a /common/ period before they are compared
- Commony, returns are expressed on an annual basis, or a as effective annual rates (EARs)
- EARs can be calculated using the tools introduced in FINM1001 ($\mbox{EAR} = (1 + HPR)^\mbox{t} - 1$)

*** Discrete vs Continous Compounding
The EAR is a discrete measuree fof investment return

Continuously compounded rates $r_{cc}$ are sometimes used in practice

An EAR can be converted into an $r_{cc}$ as follows: $r_{cc} = \ln{1 + \mbox{EAR}}$

The difference between the effective and continuously compounded rates: 
- Small over short holding periods
- Large over longer holding periods


In theory, continuous compounding is preferred, given it:
- REASONS

*** Expected Return and Standard Deviation

Investors cannot be certain about the HPR, because of uncertainty about future asset values

$$Funny E(r) = \sigma_{s}\mbox{Pr}(s)r(s)$$

with 
- Pr(s) = probabilty of bscenario occuring
- r(s) is return given that scenario

Standard deviation does not differentiate between upside and downside risk

*** Time Series Analysie of Historical Returns

While historical data analysis can form the basis of expected return and risk estimation, historical data reveals 
the HPRs realized over specific perieds, not what investors expected them to be.
Therefore, we must HDS to make /inferences/ about the probablity distributions observed HPRs were drawn from.

more thingies, copy paste this shit from further up

